export const SELECT_TOOL_LINE = "SELECT_TOOL_LINE";
export const SELECT_SIZE = "SELECT_SIZE";
export const SELECT_SHADOW_PARAMETER_BLUR = "SELECT_SHADOW_PARAMETER_BLUR";
export const SELECT_SHADOW_PARAMETER_OFFSET_X =
  "SELECT_SHADOW_PARAMETER_OFFSET_X";
export const SELECT_SHADOW_PARAMETER_OFFSET_Y =
  "SELECT_SHADOW_PARAMETER_OFFSET_Y";
export const SELECT_BUBBLES_PATTERN = "SELECT_BUBBLES_PATTERN";
export const SELECT_NESTED_PATTERN = "SELECT_NESTED_PATTERN";
export const SELECT_OPACITY = "SELECT_OPACITY";
export const SELECT_LINE_JOIN = "SELECT_LINE_JOIN";
export const SELECT_CIRCLE_TOOL = "SELECT_CIRCLE_TOOL";
export const SELECT_LINE_TOOL = "SELECT_LINE_TOOL";
export const SELECT_RECTANGLE_TOOL = "SELECT_RECTANGLE_TOOL";
export const SELECT_SQUARE_TOOL = "SELECT_SQUARE_TOOL";
export const SELECT_STROKE_STYLE = "SELECT_STROKE_STYLE";
export const SELECT_SHADOW_COLOR = "SELECT_SHADOW_COLOR";
export const SELECT_FILL_STYLE = "SELECT_FILL_STYLE";

export const FETCH_COLLECTION_BEGIN = "FETCH_COLLECTION_BEGIN";
export const FETCH_COLLECTION_SUCCESS = "FETCH_COLLECTION_SUCCESS";
export const FETCH_COLLECTION_FAILURE = "FETCH_COLLECTION_FAILURE";

export const ADD_COLLECTION_ITEM_BEGIN = "ADD_COLLECTION_ITEM_BEGIN";
export const ADD_COLLECTION_ITEM_SUCCESS = "ADD_COLLECTION_ITEM_SUCCESS";
export const ADD_COLLECTION_ITEM_FAILURE = "ADD_COLLECTION_ITEM_FAILURE";

export const UPLOAD_IMAGE_BEGIN = "UPLOAD_IMAGE_BEGIN";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";
